// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bingo_item_type::BingoItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bingo_item`.
///
/// Obtain a handle from the [`BingoItemTableAccess::bingo_item`] method on [`super::RemoteTables`],
/// like `ctx.db.bingo_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bingo_item().on_insert(...)`.
pub struct BingoItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<BingoItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bingo_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BingoItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BingoItemTableHandle`], which mediates access to the table `bingo_item`.
    fn bingo_item(&self) -> BingoItemTableHandle<'_>;
}

impl BingoItemTableAccess for super::RemoteTables {
    fn bingo_item(&self) -> BingoItemTableHandle<'_> {
        BingoItemTableHandle {
            imp: self.imp.get_table::<BingoItem>("bingo_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BingoItemInsertCallbackId(__sdk::CallbackId);
pub struct BingoItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BingoItemTableHandle<'ctx> {
    type Row = BingoItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BingoItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BingoItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BingoItemInsertCallbackId {
        BingoItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BingoItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BingoItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BingoItemDeleteCallbackId {
        BingoItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BingoItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BingoItem>("bingo_item");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct BingoItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BingoItemTableHandle<'ctx> {
    type UpdateCallbackId = BingoItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BingoItemUpdateCallbackId {
        BingoItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BingoItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BingoItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BingoItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `bingo_item`,
/// which allows point queries on the field of the same name
/// via the [`BingoItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bingo_item().id().find(...)`.
pub struct BingoItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BingoItem, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BingoItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `bingo_item`.
    pub fn id(&self) -> BingoItemIdUnique<'ctx> {
        BingoItemIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BingoItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<BingoItem> {
        self.imp.find(col_val)
    }
}
