// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bingo_board_type::BingoBoard;
use super::board_item_tile_type::BoardItemTile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bingo_board`.
///
/// Obtain a handle from the [`BingoBoardTableAccess::bingo_board`] method on [`super::RemoteTables`],
/// like `ctx.db.bingo_board()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bingo_board().on_insert(...)`.
pub struct BingoBoardTableHandle<'ctx> {
    imp: __sdk::TableHandle<BingoBoard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bingo_board`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BingoBoardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BingoBoardTableHandle`], which mediates access to the table `bingo_board`.
    fn bingo_board(&self) -> BingoBoardTableHandle<'_>;
}

impl BingoBoardTableAccess for super::RemoteTables {
    fn bingo_board(&self) -> BingoBoardTableHandle<'_> {
        BingoBoardTableHandle {
            imp: self.imp.get_table::<BingoBoard>("bingo_board"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BingoBoardInsertCallbackId(__sdk::CallbackId);
pub struct BingoBoardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BingoBoardTableHandle<'ctx> {
    type Row = BingoBoard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BingoBoard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BingoBoardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BingoBoardInsertCallbackId {
        BingoBoardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BingoBoardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BingoBoardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BingoBoardDeleteCallbackId {
        BingoBoardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BingoBoardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BingoBoard>("bingo_board");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct BingoBoardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BingoBoardTableHandle<'ctx> {
    type UpdateCallbackId = BingoBoardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BingoBoardUpdateCallbackId {
        BingoBoardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BingoBoardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BingoBoard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BingoBoard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `bingo_board`,
/// which allows point queries on the field of the same name
/// via the [`BingoBoardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bingo_board().id().find(...)`.
pub struct BingoBoardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BingoBoard, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BingoBoardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `bingo_board`.
    pub fn id(&self) -> BingoBoardIdUnique<'ctx> {
        BingoBoardIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BingoBoardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<BingoBoard> {
        self.imp.find(col_val)
    }
}
