// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::board_item_tile_type::BoardItemTile;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BingoBoard {
    pub id: u32,
    pub player_id: __sdk::Identity,
    pub game_session_id: u32,
    pub bingo_item_tiles: Vec<BoardItemTile>,
}

impl __sdk::InModule for BingoBoard {
    type Module = super::RemoteModule;
}
