// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheckForWinnerArgs {
    pub board_id: u32,
}

impl From<CheckForWinnerArgs> for super::Reducer {
    fn from(args: CheckForWinnerArgs) -> Self {
        Self::CheckForWinner {
            board_id: args.board_id,
        }
    }
}

impl __sdk::InModule for CheckForWinnerArgs {
    type Module = super::RemoteModule;
}

pub struct CheckForWinnerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `check_for_winner`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait check_for_winner {
    /// Request that the remote module invoke the reducer `check_for_winner` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_check_for_winner`] callbacks.
    fn check_for_winner(&self, board_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `check_for_winner`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CheckForWinnerCallbackId`] can be passed to [`Self::remove_on_check_for_winner`]
    /// to cancel the callback.
    fn on_check_for_winner(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> CheckForWinnerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_check_for_winner`],
    /// causing it not to run in the future.
    fn remove_on_check_for_winner(&self, callback: CheckForWinnerCallbackId);
}

impl check_for_winner for super::RemoteReducers {
    fn check_for_winner(&self, board_id: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("check_for_winner", CheckForWinnerArgs { board_id })
    }
    fn on_check_for_winner(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> CheckForWinnerCallbackId {
        CheckForWinnerCallbackId(self.imp.on_reducer(
            "check_for_winner",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CheckForWinner { board_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, board_id)
            }),
        ))
    }
    fn remove_on_check_for_winner(&self, callback: CheckForWinnerCallbackId) {
        self.imp.remove_on_reducer("check_for_winner", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `check_for_winner`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_check_for_winner {
    /// Set the call-reducer flags for the reducer `check_for_winner` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn check_for_winner(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_check_for_winner for super::SetReducerFlags {
    fn check_for_winner(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("check_for_winner", flags);
    }
}
