// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateBingoBoardArgs {
    pub player_id: __sdk::Identity,
    pub game_session_id: u32,
}

impl From<CreateBingoBoardArgs> for super::Reducer {
    fn from(args: CreateBingoBoardArgs) -> Self {
        Self::CreateBingoBoard {
            player_id: args.player_id,
            game_session_id: args.game_session_id,
        }
    }
}

impl __sdk::InModule for CreateBingoBoardArgs {
    type Module = super::RemoteModule;
}

pub struct CreateBingoBoardCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_bingo_board`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_bingo_board {
    /// Request that the remote module invoke the reducer `create_bingo_board` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_bingo_board`] callbacks.
    fn create_bingo_board(
        &self,
        player_id: __sdk::Identity,
        game_session_id: u32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_bingo_board`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateBingoBoardCallbackId`] can be passed to [`Self::remove_on_create_bingo_board`]
    /// to cancel the callback.
    fn on_create_bingo_board(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &u32) + Send + 'static,
    ) -> CreateBingoBoardCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_bingo_board`],
    /// causing it not to run in the future.
    fn remove_on_create_bingo_board(&self, callback: CreateBingoBoardCallbackId);
}

impl create_bingo_board for super::RemoteReducers {
    fn create_bingo_board(
        &self,
        player_id: __sdk::Identity,
        game_session_id: u32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_bingo_board",
            CreateBingoBoardArgs {
                player_id,
                game_session_id,
            },
        )
    }
    fn on_create_bingo_board(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &u32) + Send + 'static,
    ) -> CreateBingoBoardCallbackId {
        CreateBingoBoardCallbackId(self.imp.on_reducer(
            "create_bingo_board",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateBingoBoard {
                                    player_id,
                                    game_session_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_id, game_session_id)
            }),
        ))
    }
    fn remove_on_create_bingo_board(&self, callback: CreateBingoBoardCallbackId) {
        self.imp.remove_on_reducer("create_bingo_board", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_bingo_board`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_bingo_board {
    /// Set the call-reducer flags for the reducer `create_bingo_board` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_bingo_board(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_bingo_board for super::SetReducerFlags {
    fn create_bingo_board(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_bingo_board", flags);
    }
}
