// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteBingoItemArgs {
    pub bingo_item_id: u32,
}

impl From<DeleteBingoItemArgs> for super::Reducer {
    fn from(args: DeleteBingoItemArgs) -> Self {
        Self::DeleteBingoItem {
            bingo_item_id: args.bingo_item_id,
        }
    }
}

impl __sdk::InModule for DeleteBingoItemArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteBingoItemCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_bingo_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_bingo_item {
    /// Request that the remote module invoke the reducer `delete_bingo_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_bingo_item`] callbacks.
    fn delete_bingo_item(&self, bingo_item_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_bingo_item`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteBingoItemCallbackId`] can be passed to [`Self::remove_on_delete_bingo_item`]
    /// to cancel the callback.
    fn on_delete_bingo_item(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> DeleteBingoItemCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_bingo_item`],
    /// causing it not to run in the future.
    fn remove_on_delete_bingo_item(&self, callback: DeleteBingoItemCallbackId);
}

impl delete_bingo_item for super::RemoteReducers {
    fn delete_bingo_item(&self, bingo_item_id: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("delete_bingo_item", DeleteBingoItemArgs { bingo_item_id })
    }
    fn on_delete_bingo_item(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> DeleteBingoItemCallbackId {
        DeleteBingoItemCallbackId(self.imp.on_reducer(
            "delete_bingo_item",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteBingoItem { bingo_item_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, bingo_item_id)
            }),
        ))
    }
    fn remove_on_delete_bingo_item(&self, callback: DeleteBingoItemCallbackId) {
        self.imp.remove_on_reducer("delete_bingo_item", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_bingo_item`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_bingo_item {
    /// Set the call-reducer flags for the reducer `delete_bingo_item` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_bingo_item(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_bingo_item for super::SetReducerFlags {
    fn delete_bingo_item(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_bingo_item", flags);
    }
}
