// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::board_item_type::BoardItem;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameSession {
    pub id: u32,
    pub name: String,
    pub password: Option<String>,
    pub active: bool,
    pub winner: Option<__sdk::Identity>,
    pub board_items: Vec<BoardItem>,
}

impl __sdk::InModule for GameSession {
    type Module = super::RemoteModule;
}
