// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::board_item_type::BoardItem;
use super::game_session_type::GameSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_session`.
///
/// Obtain a handle from the [`GameSessionTableAccess::game_session`] method on [`super::RemoteTables`],
/// like `ctx.db.game_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_session().on_insert(...)`.
pub struct GameSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameSessionTableHandle`], which mediates access to the table `game_session`.
    fn game_session(&self) -> GameSessionTableHandle<'_>;
}

impl GameSessionTableAccess for super::RemoteTables {
    fn game_session(&self) -> GameSessionTableHandle<'_> {
        GameSessionTableHandle {
            imp: self.imp.get_table::<GameSession>("game_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameSessionInsertCallbackId(__sdk::CallbackId);
pub struct GameSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameSessionTableHandle<'ctx> {
    type Row = GameSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameSessionInsertCallbackId {
        GameSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameSessionDeleteCallbackId {
        GameSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameSession>("game_session");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct GameSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameSessionTableHandle<'ctx> {
    type UpdateCallbackId = GameSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameSessionUpdateCallbackId {
        GameSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GameSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `game_session`,
/// which allows point queries on the field of the same name
/// via the [`GameSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_session().id().find(...)`.
pub struct GameSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameSession, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameSessionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_session`.
    pub fn id(&self) -> GameSessionIdUnique<'ctx> {
        GameSessionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GameSession> {
        self.imp.find(col_val)
    }
}
