// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemCheckVote {
    pub id: u32,
    pub game_session_id: u32,
    pub bingo_item_id: u32,
    pub player_id: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for ItemCheckVote {
    type Module = super::RemoteModule;
}
