// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_check_vote_type::ItemCheckVote;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item_check_vote`.
///
/// Obtain a handle from the [`ItemCheckVoteTableAccess::item_check_vote`] method on [`super::RemoteTables`],
/// like `ctx.db.item_check_vote()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_check_vote().on_insert(...)`.
pub struct ItemCheckVoteTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemCheckVote>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item_check_vote`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemCheckVoteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemCheckVoteTableHandle`], which mediates access to the table `item_check_vote`.
    fn item_check_vote(&self) -> ItemCheckVoteTableHandle<'_>;
}

impl ItemCheckVoteTableAccess for super::RemoteTables {
    fn item_check_vote(&self) -> ItemCheckVoteTableHandle<'_> {
        ItemCheckVoteTableHandle {
            imp: self.imp.get_table::<ItemCheckVote>("item_check_vote"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemCheckVoteInsertCallbackId(__sdk::CallbackId);
pub struct ItemCheckVoteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemCheckVoteTableHandle<'ctx> {
    type Row = ItemCheckVote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemCheckVote> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemCheckVoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemCheckVoteInsertCallbackId {
        ItemCheckVoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemCheckVoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemCheckVoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemCheckVoteDeleteCallbackId {
        ItemCheckVoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemCheckVoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemCheckVote>("item_check_vote");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct ItemCheckVoteUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemCheckVoteTableHandle<'ctx> {
    type UpdateCallbackId = ItemCheckVoteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemCheckVoteUpdateCallbackId {
        ItemCheckVoteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemCheckVoteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ItemCheckVote>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemCheckVote>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `item_check_vote`,
/// which allows point queries on the field of the same name
/// via the [`ItemCheckVoteIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_check_vote().id().find(...)`.
pub struct ItemCheckVoteIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemCheckVote, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemCheckVoteTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `item_check_vote`.
    pub fn id(&self) -> ItemCheckVoteIdUnique<'ctx> {
        ItemCheckVoteIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemCheckVoteIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ItemCheckVote> {
        self.imp.find(col_val)
    }
}
