// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod bingo_board_table;
pub mod bingo_board_type;
pub mod bingo_item_table;
pub mod bingo_item_type;
pub mod board_item_tile_type;
pub mod board_item_type;
pub mod cast_check_off_vote_reducer;
pub mod check_for_winner_reducer;
pub mod create_bingo_board_reducer;
pub mod delete_bingo_item_reducer;
pub mod game_session_table;
pub mod game_session_type;
pub mod item_check_vote_table;
pub mod item_check_vote_type;
pub mod join_game_reducer;
pub mod player_item_subject_table;
pub mod player_item_subject_type;
pub mod player_session_table;
pub mod player_session_type;
pub mod player_table;
pub mod player_type;
pub mod remove_expired_votes_reducer;
pub mod remove_expired_votes_timer_table;
pub mod remove_expired_votes_timer_type;
pub mod set_name_reducer;
pub mod start_new_game_reducer;
pub mod submit_new_bingo_item_reducer;

pub use bingo_board_table::*;
pub use bingo_board_type::BingoBoard;
pub use bingo_item_table::*;
pub use bingo_item_type::BingoItem;
pub use board_item_tile_type::BoardItemTile;
pub use board_item_type::BoardItem;
pub use cast_check_off_vote_reducer::{
    cast_check_off_vote, set_flags_for_cast_check_off_vote, CastCheckOffVoteCallbackId,
};
pub use check_for_winner_reducer::{
    check_for_winner, set_flags_for_check_for_winner, CheckForWinnerCallbackId,
};
pub use create_bingo_board_reducer::{
    create_bingo_board, set_flags_for_create_bingo_board, CreateBingoBoardCallbackId,
};
pub use delete_bingo_item_reducer::{
    delete_bingo_item, set_flags_for_delete_bingo_item, DeleteBingoItemCallbackId,
};
pub use game_session_table::*;
pub use game_session_type::GameSession;
pub use item_check_vote_table::*;
pub use item_check_vote_type::ItemCheckVote;
pub use join_game_reducer::{join_game, set_flags_for_join_game, JoinGameCallbackId};
pub use player_item_subject_table::*;
pub use player_item_subject_type::PlayerItemSubject;
pub use player_session_table::*;
pub use player_session_type::PlayerSession;
pub use player_table::*;
pub use player_type::Player;
pub use remove_expired_votes_reducer::{
    remove_expired_votes, set_flags_for_remove_expired_votes, RemoveExpiredVotesCallbackId,
};
pub use remove_expired_votes_timer_table::*;
pub use remove_expired_votes_timer_type::RemoveExpiredVotesTimer;
pub use set_name_reducer::{set_flags_for_set_name, set_name, SetNameCallbackId};
pub use start_new_game_reducer::{
    set_flags_for_start_new_game, start_new_game, StartNewGameCallbackId,
};
pub use submit_new_bingo_item_reducer::{
    set_flags_for_submit_new_bingo_item, submit_new_bingo_item, SubmitNewBingoItemCallbackId,
};

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    CastCheckOffVote {
        game_session_id: u32,
        bingo_item_id: u32,
    },
    CheckForWinner {
        board_id: u32,
    },
    CreateBingoBoard {
        player_id: __sdk::Identity,
        game_session_id: u32,
    },
    DeleteBingoItem {
        bingo_item_id: u32,
    },
    JoinGame {
        game_session_id: u32,
        password: Option<String>,
    },
    RemoveExpiredVotes {
        timer: RemoveExpiredVotesTimer,
    },
    SetName {
        name: String,
    },
    StartNewGame {
        name: String,
        password: Option<String>,
    },
    SubmitNewBingoItem {
        body: String,
        subject_players: Option<Vec<__sdk::Identity>>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::CastCheckOffVote { .. } => "cast_check_off_vote",
            Reducer::CheckForWinner { .. } => "check_for_winner",
            Reducer::CreateBingoBoard { .. } => "create_bingo_board",
            Reducer::DeleteBingoItem { .. } => "delete_bingo_item",
            Reducer::JoinGame { .. } => "join_game",
            Reducer::RemoveExpiredVotes { .. } => "remove_expired_votes",
            Reducer::SetName { .. } => "set_name",
            Reducer::StartNewGame { .. } => "start_new_game",
            Reducer::SubmitNewBingoItem { .. } => "submit_new_bingo_item",
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "cast_check_off_vote" => Ok(__sdk::parse_reducer_args::<
                cast_check_off_vote_reducer::CastCheckOffVoteArgs,
            >("cast_check_off_vote", &value.args)?
            .into()),
            "check_for_winner" => Ok(__sdk::parse_reducer_args::<
                check_for_winner_reducer::CheckForWinnerArgs,
            >("check_for_winner", &value.args)?
            .into()),
            "create_bingo_board" => Ok(__sdk::parse_reducer_args::<
                create_bingo_board_reducer::CreateBingoBoardArgs,
            >("create_bingo_board", &value.args)?
            .into()),
            "delete_bingo_item" => Ok(__sdk::parse_reducer_args::<
                delete_bingo_item_reducer::DeleteBingoItemArgs,
            >("delete_bingo_item", &value.args)?
            .into()),
            "join_game" => Ok(
                __sdk::parse_reducer_args::<join_game_reducer::JoinGameArgs>(
                    "join_game",
                    &value.args,
                )?
                .into(),
            ),
            "remove_expired_votes" => Ok(__sdk::parse_reducer_args::<
                remove_expired_votes_reducer::RemoveExpiredVotesArgs,
            >("remove_expired_votes", &value.args)?
            .into()),
            "set_name" => Ok(__sdk::parse_reducer_args::<set_name_reducer::SetNameArgs>(
                "set_name",
                &value.args,
            )?
            .into()),
            "start_new_game" => Ok(__sdk::parse_reducer_args::<
                start_new_game_reducer::StartNewGameArgs,
            >("start_new_game", &value.args)?
            .into()),
            "submit_new_bingo_item" => Ok(__sdk::parse_reducer_args::<
                submit_new_bingo_item_reducer::SubmitNewBingoItemArgs,
            >("submit_new_bingo_item", &value.args)?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    bingo_board: __sdk::TableUpdate<BingoBoard>,
    bingo_item: __sdk::TableUpdate<BingoItem>,
    game_session: __sdk::TableUpdate<GameSession>,
    item_check_vote: __sdk::TableUpdate<ItemCheckVote>,
    player: __sdk::TableUpdate<Player>,
    player_item_subject: __sdk::TableUpdate<PlayerItemSubject>,
    player_session: __sdk::TableUpdate<PlayerSession>,
    remove_expired_votes_timer: __sdk::TableUpdate<RemoveExpiredVotesTimer>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "bingo_board" => {
                    db_update.bingo_board = bingo_board_table::parse_table_update(table_update)?
                }
                "bingo_item" => {
                    db_update.bingo_item = bingo_item_table::parse_table_update(table_update)?
                }
                "game_session" => {
                    db_update.game_session = game_session_table::parse_table_update(table_update)?
                }
                "item_check_vote" => {
                    db_update.item_check_vote =
                        item_check_vote_table::parse_table_update(table_update)?
                }
                "player" => db_update.player = player_table::parse_table_update(table_update)?,
                "player_item_subject" => {
                    db_update.player_item_subject =
                        player_item_subject_table::parse_table_update(table_update)?
                }
                "player_session" => {
                    db_update.player_session =
                        player_session_table::parse_table_update(table_update)?
                }
                "remove_expired_votes_timer" => {
                    db_update.remove_expired_votes_timer =
                        remove_expired_votes_timer_table::parse_table_update(table_update)?
                }

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.bingo_board = cache
            .apply_diff_to_table::<BingoBoard>("bingo_board", &self.bingo_board)
            .with_updates_by_pk(|row| &row.id);
        diff.bingo_item = cache
            .apply_diff_to_table::<BingoItem>("bingo_item", &self.bingo_item)
            .with_updates_by_pk(|row| &row.id);
        diff.game_session = cache
            .apply_diff_to_table::<GameSession>("game_session", &self.game_session)
            .with_updates_by_pk(|row| &row.id);
        diff.item_check_vote = cache
            .apply_diff_to_table::<ItemCheckVote>("item_check_vote", &self.item_check_vote)
            .with_updates_by_pk(|row| &row.id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.player_item_subject = cache.apply_diff_to_table::<PlayerItemSubject>(
            "player_item_subject",
            &self.player_item_subject,
        );
        diff.player_session =
            cache.apply_diff_to_table::<PlayerSession>("player_session", &self.player_session);
        diff.remove_expired_votes_timer = cache
            .apply_diff_to_table::<RemoveExpiredVotesTimer>(
                "remove_expired_votes_timer",
                &self.remove_expired_votes_timer,
            )
            .with_updates_by_pk(|row| &row.scheduled_id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    bingo_board: __sdk::TableAppliedDiff<'r, BingoBoard>,
    bingo_item: __sdk::TableAppliedDiff<'r, BingoItem>,
    game_session: __sdk::TableAppliedDiff<'r, GameSession>,
    item_check_vote: __sdk::TableAppliedDiff<'r, ItemCheckVote>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_item_subject: __sdk::TableAppliedDiff<'r, PlayerItemSubject>,
    player_session: __sdk::TableAppliedDiff<'r, PlayerSession>,
    remove_expired_votes_timer: __sdk::TableAppliedDiff<'r, RemoveExpiredVotesTimer>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<BingoBoard>("bingo_board", &self.bingo_board, event);
        callbacks.invoke_table_row_callbacks::<BingoItem>("bingo_item", &self.bingo_item, event);
        callbacks.invoke_table_row_callbacks::<GameSession>(
            "game_session",
            &self.game_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ItemCheckVote>(
            "item_check_vote",
            &self.item_check_vote,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerItemSubject>(
            "player_item_subject",
            &self.player_item_subject,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerSession>(
            "player_session",
            &self.player_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RemoveExpiredVotesTimer>(
            "remove_expired_votes_timer",
            &self.remove_expired_votes_timer,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        bingo_board_table::register_table(client_cache);
        bingo_item_table::register_table(client_cache);
        game_session_table::register_table(client_cache);
        item_check_vote_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_item_subject_table::register_table(client_cache);
        player_session_table::register_table(client_cache);
        remove_expired_votes_timer_table::register_table(client_cache);
    }
}
