// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_session_type::PlayerSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_session`.
///
/// Obtain a handle from the [`PlayerSessionTableAccess::player_session`] method on [`super::RemoteTables`],
/// like `ctx.db.player_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_session().on_insert(...)`.
pub struct PlayerSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerSessionTableHandle`], which mediates access to the table `player_session`.
    fn player_session(&self) -> PlayerSessionTableHandle<'_>;
}

impl PlayerSessionTableAccess for super::RemoteTables {
    fn player_session(&self) -> PlayerSessionTableHandle<'_> {
        PlayerSessionTableHandle {
            imp: self.imp.get_table::<PlayerSession>("player_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerSessionInsertCallbackId(__sdk::CallbackId);
pub struct PlayerSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerSessionTableHandle<'ctx> {
    type Row = PlayerSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSessionInsertCallbackId {
        PlayerSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSessionDeleteCallbackId {
        PlayerSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerSession>("player_session");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
