// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::remove_expired_votes_timer_type::RemoveExpiredVotesTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveExpiredVotesArgs {
    pub timer: RemoveExpiredVotesTimer,
}

impl From<RemoveExpiredVotesArgs> for super::Reducer {
    fn from(args: RemoveExpiredVotesArgs) -> Self {
        Self::RemoveExpiredVotes { timer: args.timer }
    }
}

impl __sdk::InModule for RemoveExpiredVotesArgs {
    type Module = super::RemoteModule;
}

pub struct RemoveExpiredVotesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_expired_votes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_expired_votes {
    /// Request that the remote module invoke the reducer `remove_expired_votes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_remove_expired_votes`] callbacks.
    fn remove_expired_votes(&self, timer: RemoveExpiredVotesTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `remove_expired_votes`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RemoveExpiredVotesCallbackId`] can be passed to [`Self::remove_on_remove_expired_votes`]
    /// to cancel the callback.
    fn on_remove_expired_votes(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &RemoveExpiredVotesTimer) + Send + 'static,
    ) -> RemoveExpiredVotesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_remove_expired_votes`],
    /// causing it not to run in the future.
    fn remove_on_remove_expired_votes(&self, callback: RemoveExpiredVotesCallbackId);
}

impl remove_expired_votes for super::RemoteReducers {
    fn remove_expired_votes(&self, timer: RemoveExpiredVotesTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("remove_expired_votes", RemoveExpiredVotesArgs { timer })
    }
    fn on_remove_expired_votes(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &RemoveExpiredVotesTimer) + Send + 'static,
    ) -> RemoveExpiredVotesCallbackId {
        RemoveExpiredVotesCallbackId(self.imp.on_reducer(
            "remove_expired_votes",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RemoveExpiredVotes { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_remove_expired_votes(&self, callback: RemoveExpiredVotesCallbackId) {
        self.imp
            .remove_on_reducer("remove_expired_votes", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `remove_expired_votes`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_remove_expired_votes {
    /// Set the call-reducer flags for the reducer `remove_expired_votes` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn remove_expired_votes(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_remove_expired_votes for super::SetReducerFlags {
    fn remove_expired_votes(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("remove_expired_votes", flags);
    }
}
