// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::remove_expired_votes_timer_type::RemoveExpiredVotesTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `remove_expired_votes_timer`.
///
/// Obtain a handle from the [`RemoveExpiredVotesTimerTableAccess::remove_expired_votes_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.remove_expired_votes_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.remove_expired_votes_timer().on_insert(...)`.
pub struct RemoveExpiredVotesTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<RemoveExpiredVotesTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `remove_expired_votes_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RemoveExpiredVotesTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RemoveExpiredVotesTimerTableHandle`], which mediates access to the table `remove_expired_votes_timer`.
    fn remove_expired_votes_timer(&self) -> RemoveExpiredVotesTimerTableHandle<'_>;
}

impl RemoveExpiredVotesTimerTableAccess for super::RemoteTables {
    fn remove_expired_votes_timer(&self) -> RemoveExpiredVotesTimerTableHandle<'_> {
        RemoveExpiredVotesTimerTableHandle {
            imp: self
                .imp
                .get_table::<RemoveExpiredVotesTimer>("remove_expired_votes_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RemoveExpiredVotesTimerInsertCallbackId(__sdk::CallbackId);
pub struct RemoveExpiredVotesTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RemoveExpiredVotesTimerTableHandle<'ctx> {
    type Row = RemoveExpiredVotesTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RemoveExpiredVotesTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RemoveExpiredVotesTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RemoveExpiredVotesTimerInsertCallbackId {
        RemoveExpiredVotesTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RemoveExpiredVotesTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RemoveExpiredVotesTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RemoveExpiredVotesTimerDeleteCallbackId {
        RemoveExpiredVotesTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RemoveExpiredVotesTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<RemoveExpiredVotesTimer>("remove_expired_votes_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct RemoveExpiredVotesTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RemoveExpiredVotesTimerTableHandle<'ctx> {
    type UpdateCallbackId = RemoveExpiredVotesTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RemoveExpiredVotesTimerUpdateCallbackId {
        RemoveExpiredVotesTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RemoveExpiredVotesTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RemoveExpiredVotesTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RemoveExpiredVotesTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `remove_expired_votes_timer`,
/// which allows point queries on the field of the same name
/// via the [`RemoveExpiredVotesTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.remove_expired_votes_timer().scheduled_id().find(...)`.
pub struct RemoveExpiredVotesTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RemoveExpiredVotesTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RemoveExpiredVotesTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `remove_expired_votes_timer`.
    pub fn scheduled_id(&self) -> RemoveExpiredVotesTimerScheduledIdUnique<'ctx> {
        RemoveExpiredVotesTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RemoveExpiredVotesTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RemoveExpiredVotesTimer> {
        self.imp.find(col_val)
    }
}
