// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartNewGameArgs {
    pub name: String,
    pub password: Option<String>,
}

impl From<StartNewGameArgs> for super::Reducer {
    fn from(args: StartNewGameArgs) -> Self {
        Self::StartNewGame {
            name: args.name,
            password: args.password,
        }
    }
}

impl __sdk::InModule for StartNewGameArgs {
    type Module = super::RemoteModule;
}

pub struct StartNewGameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_new_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_new_game {
    /// Request that the remote module invoke the reducer `start_new_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_start_new_game`] callbacks.
    fn start_new_game(&self, name: String, password: Option<String>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `start_new_game`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StartNewGameCallbackId`] can be passed to [`Self::remove_on_start_new_game`]
    /// to cancel the callback.
    fn on_start_new_game(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &Option<String>) + Send + 'static,
    ) -> StartNewGameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_start_new_game`],
    /// causing it not to run in the future.
    fn remove_on_start_new_game(&self, callback: StartNewGameCallbackId);
}

impl start_new_game for super::RemoteReducers {
    fn start_new_game(&self, name: String, password: Option<String>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("start_new_game", StartNewGameArgs { name, password })
    }
    fn on_start_new_game(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &Option<String>) + Send + 'static,
    ) -> StartNewGameCallbackId {
        StartNewGameCallbackId(self.imp.on_reducer(
            "start_new_game",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::StartNewGame { name, password },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, password)
            }),
        ))
    }
    fn remove_on_start_new_game(&self, callback: StartNewGameCallbackId) {
        self.imp.remove_on_reducer("start_new_game", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `start_new_game`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_start_new_game {
    /// Set the call-reducer flags for the reducer `start_new_game` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn start_new_game(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_start_new_game for super::SetReducerFlags {
    fn start_new_game(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("start_new_game", flags);
    }
}
