// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitNewBingoItemArgs {
    pub body: String,
    pub subject_players: Option<Vec<__sdk::Identity>>,
}

impl From<SubmitNewBingoItemArgs> for super::Reducer {
    fn from(args: SubmitNewBingoItemArgs) -> Self {
        Self::SubmitNewBingoItem {
            body: args.body,
            subject_players: args.subject_players,
        }
    }
}

impl __sdk::InModule for SubmitNewBingoItemArgs {
    type Module = super::RemoteModule;
}

pub struct SubmitNewBingoItemCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_new_bingo_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_new_bingo_item {
    /// Request that the remote module invoke the reducer `submit_new_bingo_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_submit_new_bingo_item`] callbacks.
    fn submit_new_bingo_item(
        &self,
        body: String,
        subject_players: Option<Vec<__sdk::Identity>>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `submit_new_bingo_item`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SubmitNewBingoItemCallbackId`] can be passed to [`Self::remove_on_submit_new_bingo_item`]
    /// to cancel the callback.
    fn on_submit_new_bingo_item(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &Option<Vec<__sdk::Identity>>)
            + Send
            + 'static,
    ) -> SubmitNewBingoItemCallbackId;
    /// Cancel a callback previously registered by [`Self::on_submit_new_bingo_item`],
    /// causing it not to run in the future.
    fn remove_on_submit_new_bingo_item(&self, callback: SubmitNewBingoItemCallbackId);
}

impl submit_new_bingo_item for super::RemoteReducers {
    fn submit_new_bingo_item(
        &self,
        body: String,
        subject_players: Option<Vec<__sdk::Identity>>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "submit_new_bingo_item",
            SubmitNewBingoItemArgs {
                body,
                subject_players,
            },
        )
    }
    fn on_submit_new_bingo_item(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &Option<Vec<__sdk::Identity>>)
            + Send
            + 'static,
    ) -> SubmitNewBingoItemCallbackId {
        SubmitNewBingoItemCallbackId(self.imp.on_reducer(
            "submit_new_bingo_item",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::SubmitNewBingoItem {
                                    body,
                                    subject_players,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, body, subject_players)
            }),
        ))
    }
    fn remove_on_submit_new_bingo_item(&self, callback: SubmitNewBingoItemCallbackId) {
        self.imp
            .remove_on_reducer("submit_new_bingo_item", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `submit_new_bingo_item`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_submit_new_bingo_item {
    /// Set the call-reducer flags for the reducer `submit_new_bingo_item` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn submit_new_bingo_item(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_submit_new_bingo_item for super::SetReducerFlags {
    fn submit_new_bingo_item(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("submit_new_bingo_item", flags);
    }
}
