version: '3.8'

services:
  spacetimedb:
    image: clockworklabs/spacetime
    command: start --data-dir=/stdb
    user: root
    ports:
      - "3030:3000"
    volumes:
      - spacetimedb-data:/stdb
    restart: unless-stopped
    pull_policy: always
    networks:
      - bingo-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - spacetimedb
    restart: unless-stopped
    networks:
      - bingo-network

networks:
  bingo-network:
    driver: bridge

volumes:
  spacetimedb-data:
