// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { BoardItemTile as __BoardItemTile } from "./board_item_tile_type";

export type BingoBoard = {
  id: number,
  playerId: Identity,
  gameSessionId: number,
  bingoItemTiles: __BoardItemTile[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace BingoBoard {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("playerId", AlgebraicType.createIdentityType()),
      new ProductTypeElement("gameSessionId", AlgebraicType.createU32Type()),
      new ProductTypeElement("bingoItemTiles", AlgebraicType.createArrayType(__BoardItemTile.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: BingoBoard): void {
    BingoBoard.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): BingoBoard {
    return BingoBoard.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


