// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { BoardItem as __BoardItem } from "./board_item_type";

export type GameSession = {
  id: number,
  name: string,
  active: boolean,
  winner: Identity | undefined,
  boardItems: __BoardItem[],
  started: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameSession {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("active", AlgebraicType.createBoolType()),
      new ProductTypeElement("winner", AlgebraicType.createOptionType(AlgebraicType.createIdentityType())),
      new ProductTypeElement("boardItems", AlgebraicType.createArrayType(__BoardItem.getTypeScriptAlgebraicType())),
      new ProductTypeElement("started", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameSession): void {
    GameSession.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameSession {
    return GameSession.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


