[package]
name = "yew-client"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
spacetimedb-sdk = "1.1.1"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }

# spacetime generate --lang rust --out-dir yew-client/src/module_bindings --project-path server